# Generated by Django 5.1.7 on 2025-09-14 23:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('domestic_transfer', 'Domestic Transfer'), ('inter_bank', 'Inter-Bank Transfer'), ('wire', 'Wire Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(default='savings', max_length=20)),
                ('password_confirm', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomesticTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('domestic_transfer', 'Domestic Transfer'), ('inter_bank', 'Inter-Bank Transfer'), ('wire', 'Wire Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(default='savings', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WireTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('domestic_transfer', 'Domestic Transfer'), ('inter_bank', 'Inter-Bank Transfer'), ('wire', 'Wire Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=20)),
                ('iban', models.CharField(max_length=34)),
                ('bank_name', models.CharField(max_length=100)),
                ('swift_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('account_type', models.CharField(default='savings', max_length=20)),
                ('password_confirm', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
